### ISSUE TITLE
Undefined symbol: _td_json_client_send ...

### ISSUE THREAD

**Issue by maxskorr** [modestman/tdlib-swift#2]
Hello!

I cloned the repo, but getting some errors when trying to build it for an iOS device (or a simulator):

![Screenshot 2020-11-20 at 10 21 07](https://user-images.githubusercontent.com/3083784/99771568-69da7280-2b1a-11eb-887f-b08883c6a880.png)

![image](https://user-images.githubusercontent.com/3083784/99771806-c6d62880-2b1a-11eb-8bbf-78ad6886cad2.png)

Do I have to perform any extra steps to re-compile tdlib for my target platforms or something like that? Could you please point me to the right direction?

**Comment by modestman** [comment]
Hello!

I think you not used git for clone the repo, you probably downloaded a .zip file with code. 
This repo contains large binary files for precompiled TdLib. Unfortunately, when downloading a .zip, the GitHub doesn't copy the necessary files completely.

Try clone repo with git
```shell
git clone git@github.com:modestman/tdlib-swift.git
```
Or download binaries manually: `TdLib.xcframework/ios-x86_64-simulator/TdLib.framework/TdLib` (and `ios-arm64`), and replace it in your file system.

**Comment by maxskorr** [comment]
Wow, thank you for a prompt response!

It's interesting that I used exactly git clone for cloning, however it still would not fully download these files:

![image](https://user-images.githubusercontent.com/3083784/99789722-1543f100-2b34-11eb-9d6a-8eac7db9b184.png)

Thank you for your help, downloading original files from git & placing them under the location you mentioned resolved the issue

**Comment by modestman** [comment]
Maybe you should install the [Git LFS](https://git-lfs.github.com/) extension for properly pulling a large files from repo
