### ISSUE TITLE
func SearchChatMessages how to pass null in parameter

### ISSUE THREAD

**Issue by AKHMAD2000** [modestman/tdlib-swift#3]
Hello! Thanks for the library. I want to get filtered messages by searchChatMessages method and in the comment written pass null for the sender to get all messages no exactly from a specific sender but how can I pass null in swift?
/// - Parameter sender: If not null, only messages sent by the specified sender will be returned. Not supported in secret chats

**Comment by modestman** [comment]
Hello @AKHMAD2000!
The `searchChatMessages` method automatically generated form the [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) spec. There may be an error in the specification. I created an [issue](https://github.com/tdlib/td/issues/1536) in tdlib repo. If the spec is updated, I will update generated Swift code.

But now you can yourself mark `MessageSender` as Optional in the `TdApi.swift` and `SearchChatMessages.swift` files
```swift
public struct SearchChatMessages: Codable {
    // ...
    public let sender: MessageSender?

    public init(
        // ...
        sender: MessageSender?
    ) {
        // ...
        self.sender = sender
    }
}
```
It should work, try it.

**Comment by AKHMAD2000** [comment]
It worked thank you!

**Comment by dchudov** [comment]
Same issue with **createNewSupergroupChat** function, where **location** parameter is mandatory, so we can create only location-based group chat (affects its privacy, no matter how private it is). I've marked this parameter optional manually.

**Comment by modestman** [comment]
@dchudov Hello.
In this [issue](https://github.com/tdlib/td/issues/1536) @levlam said:
> Any direct or indirect function parameter can be specified to be null. In all function null objects are allowed by TDLib in incoming requests. Passing null may result in a valid or invalid request depending on the function or values of other parameters.

It means you can manually mark any function parameter as optional in generated API.
I will try to update API soon.

**Comment by dchudov** [comment]
Thank you! I just mentioned this another particular situation for those who search solution.
